import o3manage
from docopt import docopt

import logging

def o3crinstance():
    """o3crinstance

    Usage:
        o3crinstance <name> --port-base=<number>
            [(-v | --verbose)]
            [(-q | --quiet)]
    
    Options:
    --port-base=<number>    The first three digits of the port number(s).
                            The subsequent digit will be generated by the
                            programm.
    -v --verbose            Be more verbose
    """
    arguments = docopt(o3crinstance.__doc__)
    name = arguments["<name>"]
    port_base = arguments["--port-base"]
    verbose = arguments["--verbose"]
    quiet = arguments["--quiet"]

    if quiet:
        logging.basicConfig(level = logging.CRITICAL)
    elif verbose:
        logging.basicConfig(level = logging.DEBUG)
    else:
        logging.basicConfig(level = logging.INFO)

    instance = o3manage.OdooInstance.create(name, port_base)
    
    print("-" * 12)
    print("Creating finished.")
    print("Your odoo instance is in {}".format(instance.root_dir))
    print("admin_passwd = {}".format(instance.admin_passwd))
    print("")
